P1Project/P1Main/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using P1Main.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace P1Main.Controllers
{
  public class LandingController : Controller
  {
    private readonly ILogger<LandingController> _logger;

    public LandingController(ILogger<LandingController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    public IActionResult Privacy()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

P1Project/P1Main/Controllers/LoginController.cs
using BusinessLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P1Main.Controllers
{
  public class LoginController : Controller
  {
    private readonly IDbInteract _DbInteract;
    // create a constructor into which the business layer dependency will be injected (in Startup.cs)
    public LoginController(IDbInteract dbInteract)
    {
      this._DbInteract = dbInteract;
    }

    // GET: LoginController
    public ActionResult Index()
    {
      return View();
    }

    // GET: LoginController/Details/5
    public ActionResult Details(int id)
    {
      return View();
    }

    // GET: LoginController/Create
    public ActionResult LoginCustomer()
    {
      return View();
    }

    [HttpPost]
    public ActionResult VerifyLoginCustomer(CustomerModel customerLogin)
    {
      bool SuccessfulVerification = _DbInteract.VerifyCustomer(customerLogin.Username, customerLogin.Password);
      if (SuccessfulVerification)
      {
        CustomerModel customer = _DbInteract.GetCustomer(customerLogin.Username, customerLogin.Password);
        return RedirectToAction("Index", "Home", customer);
      }
      else
        return View("LoginCustomer");
    }

    // POST: LoginController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    // GET: LoginController/Edit/5
    public ActionResult Edit(int id)
    {
      return View();
    }

    // POST: LoginController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }

    // GET: LoginController/Delete/5
    public ActionResult Delete(int id)
    {
      return View();
    }

    // POST: LoginController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
      try
      {
        return RedirectToAction(nameof(Index));
      }
      catch
      {
        return View();
      }
    }
  }
}

P1Project/P1Main/Views/Login/LoginCustomer.cshtml
@model ModelsLibrary.CustomerModel

@{
  ViewData["Title"] = "Login";
}
@{
  Layout = "~/Views/Shared/_Layout_Protected.cshtml";
}



<h1>LoginCustomer</h1>

<div class="row">
  <div class="col-md-4">
    <form asp-action="VerifyLoginCustomer">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Password" class="control-label"></label>
        <input asp-for="Password" class="form-control" />
        <span asp-validation-for="Password" class="text-danger"></span>
      </div>
      <div class="form-group">
        <input type="submit" value="Login" class="btn btn-primary" />
      </div>
    </form>
  </div>
</div>

<div>
  <a asp-controller="Landing" asp-action="Index">Back to Landing</a>
</div>

@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

P1Project/P1Main/Views/Login/VerifyLoginCustomer.cshtml
@model ModelsLibrary.CustomerModel

@{
    ViewData["Title"] = "VerifyLoginCustomer";
}

<h1>VerifyLoginCustomer</h1>

<dl>
  <dt class="col-sm-2">
    @Html.DisplayNameFor(model => model.Username)
  </dt>
  <dd class="col-sm-10">
    @Html.DisplayFor(model => model.Username)
  </dd>
  <dt class="col-sm-2">
    @Html.DisplayNameFor(model => model.Password)
  </dt>
  <dd class="col-sm-10">
    @Html.DisplayFor(model => model.Password)
  </dd>
</dl>

<div>
  @Html.ActionLink("Home", "Index", Model)
</div>